### ISSUE TITLE
Git Clone failing

### ISSUE THREAD

**Issue by ovalba** [awslabs/yesiscan#5]
./yesiscan --no-backend-scancode https://github.com/aws/amazon-cloudwatch-agent

Results:
main: failed: repository not found

**Comment by amznpurple** [comment]
So I've been tracking this down. Here's why it's broken:

https://github.com/aws/amazon-cloudwatch-agent/commit/1c07e074c34707a4470707dbcc7a2fa743398efb

Look at their commit. They did something weird on purpose. I'm trying now to decide whether it's valid git (I guess so) but seeing as it's non-standard, that's why it's broken. Fun issue!

**Comment by amznpurple** [comment]
This is now fixed in f0856bc1c10935ad9589d2fce59e7133749bd410
