### ISSUE TITLE
Newly installed yesiscan on Linux was unable to download and use "configs"

### ISSUE THREAD

**Issue by MarkAtwood** [awslabs/yesiscan#68]

**Comment by amznpurple** [comment]
This was a fun one. Long story short, the newly added auto config code was downloading the first config, and then since we told it not to check again for N seconds, didn't proceed with the additional configs that some custom config files suggest.

This is all fixed in version v0.0.11 (as tagged.

Thank you for reporting!

PS: The fix in the code is super fun too if you're curious and want to check.
