### ISSUE TITLE
Send scan output to file

### ISSUE THREAD

**Issue by tapdiego-amzn** [awslabs/yesiscan#8]
Add a `-o` or similar option to send scan output to a file instead of STDOUT.

**Comment by amznpurple** [comment]
If they are using the console, would you prefer the file as plain text as it was in the terminal? As html but looking like the console? As html in the graphical way it is seen in the webui? As a pdf of any of those?

If they are using the webui would you like it to be in html? As a pdf?

Cheers

**Comment by tapdiego-amzn** [comment]
I think the output format should be what better matches the chosen execution mode — that is, plain text if using the console, or HTML if using the web UI. Not a big fan of PDF for either of those.

**Comment by amznpurple** [comment]
Awesome thanks! For the text output: what would you like to see for the URL? I have two values that I use everywhere: a friendly "display" UID, and also a clickable link that takes you directly to the github page for example. Since it's just plain text, I am going to only show the display one, but if there is something better we should do instead please let me know.

Eg: we could show:

`display / link`

or something, but I think it will be too wide.

**Comment by tapdiego-amzn** [comment]
Whatever makes it easier to retrieve the original file for validation will be best IMHO, so the URL would be my choice.

**Comment by amznpurple** [comment]
This is now implemented and released in v0.0.7
Please have a try and let me know what you think!
